package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:31:36 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActivitiesByIssue generated by hbm2java
 */
@Entity
@Table(name = "activities_by_issue", catalog = "redmine")
public class ActivitiesByIssue implements java.io.Serializable {

	private ActivitiesByIssueId id;

	public ActivitiesByIssue() {
	}

	public ActivitiesByIssue(ActivitiesByIssueId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "issueId", column = @Column(name = "issue_id", nullable = false)),
			@AttributeOverride(name = "parentId", column = @Column(name = "parent_id")),
			@AttributeOverride(name = "activity", column = @Column(name = "activity", nullable = false, length = 30)),
			@AttributeOverride(name = "investedTime", column = @Column(name = "invested_time", precision = 22, scale = 0)),
			@AttributeOverride(name = "subject", column = @Column(name = "subject", nullable = false)) })
	public ActivitiesByIssueId getId() {
		return this.id;
	}

	public void setId(ActivitiesByIssueId id) {
		this.id = id;
	}

}
