package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:31:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivitiesByUserId generated by hbm2java
 */
@Embeddable
public class ActivitiesByUserId implements java.io.Serializable {

	private int id;
	private int activityId;
	private String name;
	private Double totalTime;

	public ActivitiesByUserId() {
	}

	public ActivitiesByUserId(int id, int activityId, String name) {
		this.id = id;
		this.activityId = activityId;
		this.name = name;
	}

	public ActivitiesByUserId(int id, int activityId, String name,
			Double totalTime) {
		this.id = id;
		this.activityId = activityId;
		this.name = name;
		this.totalTime = totalTime;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "activity_id", nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "total_time", precision = 22, scale = 0)
	public Double getTotalTime() {
		return this.totalTime;
	}

	public void setTotalTime(Double totalTime) {
		this.totalTime = totalTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivitiesByUserId))
			return false;
		ActivitiesByUserId castOther = (ActivitiesByUserId) other;

		return (this.getId() == castOther.getId())
				&& (this.getActivityId() == castOther.getActivityId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getTotalTime() == castOther.getTotalTime()) || (this
						.getTotalTime() != null
						&& castOther.getTotalTime() != null && this
						.getTotalTime().equals(castOther.getTotalTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getActivityId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getTotalTime() == null ? 0 : this.getTotalTime().hashCode());
		return result;
	}

}
