package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:31:36 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActivitiesByUser generated by hbm2java
 */
@Entity
@Table(name = "activities_by_user", catalog = "redmine")
public class ActivitiesByUser implements java.io.Serializable {

	private ActivitiesByUserId id;

	public ActivitiesByUser() {
	}

	public ActivitiesByUser(ActivitiesByUserId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 30)),
			@AttributeOverride(name = "totalTime", column = @Column(name = "total_time", precision = 22, scale = 0)) })
	public ActivitiesByUserId getId() {
		return this.id;
	}

	public void setId(ActivitiesByUserId id) {
		this.id = id;
	}

}
