package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:31:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActivitiesByProjectId generated by hbm2java
 */
@Embeddable
public class ActivitiesByProjectId implements java.io.Serializable {

	private int projectId;
	private Integer parentId;
	private String activity;
	private Double investedTime;
	private String projectName;
	private String projectDescription;

	public ActivitiesByProjectId() {
	}

	public ActivitiesByProjectId(int projectId, String activity,
			String projectName) {
		this.projectId = projectId;
		this.activity = activity;
		this.projectName = projectName;
	}

	public ActivitiesByProjectId(int projectId, Integer parentId,
			String activity, Double investedTime, String projectName,
			String projectDescription) {
		this.projectId = projectId;
		this.parentId = parentId;
		this.activity = activity;
		this.investedTime = investedTime;
		this.projectName = projectName;
		this.projectDescription = projectDescription;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "activity", nullable = false, length = 30)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "invested_time", precision = 22, scale = 0)
	public Double getInvestedTime() {
		return this.investedTime;
	}

	public void setInvestedTime(Double investedTime) {
		this.investedTime = investedTime;
	}

	@Column(name = "project_name", nullable = false)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_description", length = 65535)
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivitiesByProjectId))
			return false;
		ActivitiesByProjectId castOther = (ActivitiesByProjectId) other;

		return (this.getProjectId() == castOther.getProjectId())
				&& ((this.getParentId() == castOther.getParentId()) || (this
						.getParentId() != null
						&& castOther.getParentId() != null && this
						.getParentId().equals(castOther.getParentId())))
				&& ((this.getActivity() == castOther.getActivity()) || (this
						.getActivity() != null
						&& castOther.getActivity() != null && this
						.getActivity().equals(castOther.getActivity())))
				&& ((this.getInvestedTime() == castOther.getInvestedTime()) || (this
						.getInvestedTime() != null
						&& castOther.getInvestedTime() != null && this
						.getInvestedTime().equals(castOther.getInvestedTime())))
				&& ((this.getProjectName() == castOther.getProjectName()) || (this
						.getProjectName() != null
						&& castOther.getProjectName() != null && this
						.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getProjectDescription() == castOther
						.getProjectDescription()) || (this
						.getProjectDescription() != null
						&& castOther.getProjectDescription() != null && this
						.getProjectDescription().equals(
								castOther.getProjectDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result
				+ (getParentId() == null ? 0 : this.getParentId().hashCode());
		result = 37 * result
				+ (getActivity() == null ? 0 : this.getActivity().hashCode());
		result = 37
				* result
				+ (getInvestedTime() == null ? 0 : this.getInvestedTime()
						.hashCode());
		result = 37
				* result
				+ (getProjectName() == null ? 0 : this.getProjectName()
						.hashCode());
		result = 37
				* result
				+ (getProjectDescription() == null ? 0 : this
						.getProjectDescription().hashCode());
		return result;
	}

}
