package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 2:58:10 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BasicInfo generated by hbm2java
 */
@Entity
@Table(name = "basic_info", catalog = "redmine")
public class BasicInfo implements java.io.Serializable {

	private BasicInfoId id;

	public BasicInfo() {
	}

	public BasicInfo(BasicInfoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "tracker", column = @Column(name = "tracker", nullable = false, length = 30)),
			@AttributeOverride(name = "activity", column = @Column(name = "activity", nullable = false, length = 30)),
			@AttributeOverride(name = "projectName", column = @Column(name = "project_name", nullable = false)),
			@AttributeOverride(name = "issueSubject", column = @Column(name = "issue_subject", nullable = false)),
			@AttributeOverride(name = "issueDescription", column = @Column(name = "issue_description", length = 65535)),
			@AttributeOverride(name = "teComments", column = @Column(name = "te_comments")),
			@AttributeOverride(name = "firstname", column = @Column(name = "firstname", nullable = false, length = 30)) })
	public BasicInfoId getId() {
		return this.id;
	}

	public void setId(BasicInfoId id) {
		this.id = id;
	}

}
