package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 2:58:10 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BasicInfoId generated by hbm2java
 */
@Embeddable
public class BasicInfoId implements java.io.Serializable {

	private int id;
	private String tracker;
	private String activity;
	private String projectName;
	private String issueSubject;
	private String issueDescription;
	private String teComments;
	private String firstname;

	public BasicInfoId() {
	}

	public BasicInfoId(int id, String tracker, String activity,
			String projectName, String issueSubject, String firstname) {
		this.id = id;
		this.tracker = tracker;
		this.activity = activity;
		this.projectName = projectName;
		this.issueSubject = issueSubject;
		this.firstname = firstname;
	}

	public BasicInfoId(int id, String tracker, String activity,
			String projectName, String issueSubject, String issueDescription,
			String teComments, String firstname) {
		this.id = id;
		this.tracker = tracker;
		this.activity = activity;
		this.projectName = projectName;
		this.issueSubject = issueSubject;
		this.issueDescription = issueDescription;
		this.teComments = teComments;
		this.firstname = firstname;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tracker", nullable = false, length = 30)
	public String getTracker() {
		return this.tracker;
	}

	public void setTracker(String tracker) {
		this.tracker = tracker;
	}

	@Column(name = "activity", nullable = false, length = 30)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "project_name", nullable = false)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "issue_subject", nullable = false)
	public String getIssueSubject() {
		return this.issueSubject;
	}

	public void setIssueSubject(String issueSubject) {
		this.issueSubject = issueSubject;
	}

	@Column(name = "issue_description", length = 65535)
	public String getIssueDescription() {
		return this.issueDescription;
	}

	public void setIssueDescription(String issueDescription) {
		this.issueDescription = issueDescription;
	}

	@Column(name = "te_comments")
	public String getTeComments() {
		return this.teComments;
	}

	public void setTeComments(String teComments) {
		this.teComments = teComments;
	}

	@Column(name = "firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BasicInfoId))
			return false;
		BasicInfoId castOther = (BasicInfoId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getTracker() == castOther.getTracker()) || (this
						.getTracker() != null && castOther.getTracker() != null && this
						.getTracker().equals(castOther.getTracker())))
				&& ((this.getActivity() == castOther.getActivity()) || (this
						.getActivity() != null
						&& castOther.getActivity() != null && this
						.getActivity().equals(castOther.getActivity())))
				&& ((this.getProjectName() == castOther.getProjectName()) || (this
						.getProjectName() != null
						&& castOther.getProjectName() != null && this
						.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getIssueSubject() == castOther.getIssueSubject()) || (this
						.getIssueSubject() != null
						&& castOther.getIssueSubject() != null && this
						.getIssueSubject().equals(castOther.getIssueSubject())))
				&& ((this.getIssueDescription() == castOther
						.getIssueDescription()) || (this.getIssueDescription() != null
						&& castOther.getIssueDescription() != null && this
						.getIssueDescription().equals(
								castOther.getIssueDescription())))
				&& ((this.getTeComments() == castOther.getTeComments()) || (this
						.getTeComments() != null
						&& castOther.getTeComments() != null && this
						.getTeComments().equals(castOther.getTeComments())))
				&& ((this.getFirstname() == castOther.getFirstname()) || (this
						.getFirstname() != null
						&& castOther.getFirstname() != null && this
						.getFirstname().equals(castOther.getFirstname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getTracker() == null ? 0 : this.getTracker().hashCode());
		result = 37 * result
				+ (getActivity() == null ? 0 : this.getActivity().hashCode());
		result = 37
				* result
				+ (getProjectName() == null ? 0 : this.getProjectName()
						.hashCode());
		result = 37
				* result
				+ (getIssueSubject() == null ? 0 : this.getIssueSubject()
						.hashCode());
		result = 37
				* result
				+ (getIssueDescription() == null ? 0 : this
						.getIssueDescription().hashCode());
		result = 37
				* result
				+ (getTeComments() == null ? 0 : this.getTeComments()
						.hashCode());
		result = 37 * result
				+ (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		return result;
	}

}
