package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:31:36 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CommentsWithActivity generated by hbm2java
 */
@Entity
@Table(name = "comments_with_activity", catalog = "redmine")
public class CommentsWithActivity implements java.io.Serializable {

	private CommentsWithActivityId id;

	public CommentsWithActivity() {
	}

	public CommentsWithActivity(CommentsWithActivityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id", nullable = false)),
			@AttributeOverride(name = "activityName", column = @Column(name = "activity_name", nullable = false, length = 30)),
			@AttributeOverride(name = "comments", column = @Column(name = "comments")) })
	public CommentsWithActivityId getId() {
		return this.id;
	}

	public void setId(CommentsWithActivityId id) {
		this.id = id;
	}

}
