package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:31:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentsWithActivityId generated by hbm2java
 */
@Embeddable
public class CommentsWithActivityId implements java.io.Serializable {

	private int activityId;
	private String activityName;
	private String comments;

	public CommentsWithActivityId() {
	}

	public CommentsWithActivityId(int activityId, String activityName) {
		this.activityId = activityId;
		this.activityName = activityName;
	}

	public CommentsWithActivityId(int activityId, String activityName,
			String comments) {
		this.activityId = activityId;
		this.activityName = activityName;
		this.comments = comments;
	}

	@Column(name = "activity_id", nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	@Column(name = "activity_name", nullable = false, length = 30)
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentsWithActivityId))
			return false;
		CommentsWithActivityId castOther = (CommentsWithActivityId) other;

		return (this.getActivityId() == castOther.getActivityId())
				&& ((this.getActivityName() == castOther.getActivityName()) || (this
						.getActivityName() != null
						&& castOther.getActivityName() != null && this
						.getActivityName().equals(castOther.getActivityName())))
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActivityId();
		result = 37
				* result
				+ (getActivityName() == null ? 0 : this.getActivityName()
						.hashCode());
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		return result;
	}

}
