package poolingpeople.datacrunch.redmine;

// Generated Oct 28, 2013 5:34:10 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TotalTimePerUser generated by hbm2java
 */
@Entity
@Table(name = "total_time_per_user", catalog = "redmine")
public class TotalTimePerUser implements java.io.Serializable {

	private TotalTimePerUserId id;

	public TotalTimePerUser() {
	}

	public TotalTimePerUser(TotalTimePerUserId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "login", column = @Column(name = "login", nullable = false)),
			@AttributeOverride(name = "sum(te.hours)", column = @Column(name = "sum(te.hours)", precision = 22, scale = 0)) })
	public TotalTimePerUserId getId() {
		return this.id;
	}

	public void setId(TotalTimePerUserId id) {
		this.id = id;
	}

}
