package poolingpeople.datacrunch.redmine;
// Generated Oct 28, 2013 5:34:10 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TotalTimePerUserId generated by hbm2java
 */
@Embeddable
public class TotalTimePerUserId  implements java.io.Serializable {


     private int userId;
     private String login;
     private Double total_time;

    public TotalTimePerUserId() {
    }

	
    public TotalTimePerUserId(int userId, String login) {
        this.userId = userId;
        this.login = login;
    }
    public TotalTimePerUserId(int userId, String login, Double total_time) {
       this.userId = userId;
       this.login = login;
       this.total_time = total_time;
    }
   
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="login", nullable=false)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }


    @Column(name="total_time", precision=22, scale=0)
    public Double getTotal_time() {
        return this.total_time;
    }
    
    public void setTotal_time(Double total_time) {
        this.total_time = total_time;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TotalTimePerUserId) ) return false;
		 TotalTimePerUserId castOther = ( TotalTimePerUserId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getLogin()==castOther.getLogin()) || ( this.getLogin()!=null && castOther.getLogin()!=null && this.getLogin().equals(castOther.getLogin()) ) )
 && ( (this.getTotal_time()==castOther.getTotal_time()) || ( this.getTotal_time()!=null && castOther.getTotal_time()!=null && this.getTotal_time().equals(castOther.getTotal_time()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getLogin() == null ? 0 : this.getLogin().hashCode() );
         result = 37 * result + ( getTotal_time() == null ? 0 : this.getTotal_time().hashCode() );
         return result;
   }   


}


